# Generated by Django 4.2 on 2025-04-23 11:49
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrichain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_added', models.DateTimeField(auto_now_add=True)),
                ('item_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_slabs',
                                              to='agrichain.product')),
                ('qty', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items',
                                           to='agrichain.cart')),

            ],
        ),
    ]
